// <auto-generated />
using System;
using CSupporter.Services.Contractors.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CSupporter.Services.Contractors.Migrations
{
    [DbContext(typeof(ContractorDbContext))]
    partial class ContractorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CSupporter.Services.Contractors.Models.Contractor", b =>
                {
                    b.Property<int>("ContractorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ContractorId");

                    b.ToTable("Contractors");

                    b.HasData(
                        new
                        {
                            ContractorId = 1,
                            Address = "Warszawa, ul. Przedszkolna 15",
                            CompanyDetails = "--",
                            CompanyName = "GM Prime RN",
                            FirstName = "Richard",
                            InsertDate = new DateTime(2021, 11, 28, 12, 48, 9, 915, DateTimeKind.Local).AddTicks(121),
                            LastName = "Nowak",
                            NIP = "912-111-09-10",
                            UpdateDate = new DateTime(2021, 11, 28, 12, 48, 9, 918, DateTimeKind.Local).AddTicks(9420)
                        },
                        new
                        {
                            ContractorId = 2,
                            Address = "Gdański, ul. Mariacka 8",
                            CompanyDetails = "--",
                            CompanyName = "FUH Adrian",
                            FirstName = "Adrian",
                            InsertDate = new DateTime(2021, 11, 28, 12, 48, 9, 921, DateTimeKind.Local).AddTicks(3707),
                            LastName = "Kowalski",
                            NIP = "805-111-09-10",
                            UpdateDate = new DateTime(2021, 11, 28, 12, 48, 9, 921, DateTimeKind.Local).AddTicks(3755)
                        },
                        new
                        {
                            ContractorId = 3,
                            Address = "Wrocław, ul. Żeromskiego 10",
                            CompanyDetails = "--",
                            CompanyName = "KOMFORT",
                            FirstName = "Roman",
                            InsertDate = new DateTime(2021, 11, 28, 12, 48, 9, 921, DateTimeKind.Local).AddTicks(4018),
                            LastName = "Romanowicz",
                            NIP = "712-934-35-23",
                            UpdateDate = new DateTime(2021, 11, 28, 12, 48, 9, 921, DateTimeKind.Local).AddTicks(4026)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
